# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            pkill python3
            cd /var/www/html/GardenForce-Demo/ 
            git pull
            cd python/
            nohup python3 ./forever.py > gardenforce.log &
            systemctl reload apache2
            echo 'Deployment successful to digital ocean' 
